import json, os

cats = [
  ("Page Load & Navigation", [
    ("Home page loads under 2 seconds","GET","/","200","Critical"),
    ("Login page renders correctly","GET","/login","200","Critical"),
    ("Register page renders correctly","GET","/register","200","Critical"),
    ("Dashboard page loads after login","GET","/dashboard","200","Critical"),
    ("Offer Analyzer page loads","GET","/analyze","200","High"),
    ("Company Verifier page loads","GET","/verify","200","High"),
    ("Blacklist page loads","GET","/blacklist","200","High"),
    ("Resume Scanner page loads","GET","/resume","200","High"),
    ("Scan History page loads","GET","/history","200","High"),
    ("Settings page loads","GET","/settings","200","Medium"),
    ("About page loads","GET","/about","200","Low"),
    ("404 page displayed for unknown route","GET","/nonexistent","404","High"),
    ("Navigation menu renders all links","UI","nav-menu","visible","Critical"),
    ("Footer renders correctly","UI","footer","visible","Low"),
    ("Logo click redirects to home","UI","logo","redirect","Medium"),
    ("Browser back button works correctly","UI","back-btn","navigate","Medium"),
    ("Browser forward button works correctly","UI","fwd-btn","navigate","Medium"),
    ("Page title updates on route change","UI","page-title","updated","Medium"),
    ("Breadcrumb navigation renders correctly","UI","breadcrumb","visible","Low"),
    ("Sidebar navigation collapses on mobile","UI","sidebar","collapsed","Medium"),
    ("Sticky header remains on scroll","UI","header","sticky","Low"),
    ("Scroll-to-top button appears on scroll","UI","scroll-top","visible","Low"),
    ("Tab navigation accessible via keyboard","UI","tab-nav","accessible","High"),
    ("Deep link URL renders correct page","GET","/blacklist/scam_001","200","High"),
    ("Protected route redirects unauthenticated user to login","UI","protected","redirect","Critical"),
    ("Loading spinner shown during page transitions","UI","spinner","visible","Medium"),
    ("Page renders correctly in Firefox","UI","browser-ff","rendered","Medium"),
    ("Page renders correctly in Chrome","UI","browser-chrome","rendered","High"),
    ("Page renders correctly in Safari","UI","browser-safari","rendered","Medium"),
    ("Page renders correctly in Edge","UI","browser-edge","rendered","Medium"),
    ("Page renders on 1920x1080 desktop viewport","UI","viewport-desktop","rendered","High"),
    ("Page renders on 375x812 mobile viewport","UI","viewport-mobile","rendered","Critical"),
    ("Page renders on 768x1024 tablet viewport","UI","viewport-tablet","rendered","High"),
    ("Meta title tag set correctly on all pages","UI","meta-title","set","Medium"),
    ("Meta description tag set on all pages","UI","meta-desc","set","Medium"),
  ]),
  ("Authentication UI Flows", [
    ("Login form displays email & password fields","UI","login-form","visible","Critical"),
    ("Login form validates empty email shows error","UI","login-email","error","Critical"),
    ("Login form validates empty password shows error","UI","login-pwd","error","Critical"),
    ("Login form validates invalid email format","UI","login-email-fmt","error","High"),
    ("Login button disabled when fields empty","UI","login-btn","disabled","Medium"),
    ("Login success redirects to dashboard","UI","login-success","redirect","Critical"),
    ("Login failure shows incorrect credentials message","UI","login-fail","message","Critical"),
    ("Register form displays all required fields","UI","register-form","visible","Critical"),
    ("Register password strength meter renders","UI","pwd-strength","visible","Medium"),
    ("Register password mismatch shows error","UI","pwd-mismatch","error","High"),
    ("Register success shows welcome message","UI","register-success","message","Critical"),
    ("Forgot password link visible on login page","UI","forgot-pwd-link","visible","High"),
    ("Forgot password form accepts email input","UI","forgot-pwd-form","accepts","High"),
    ("OTP verification screen renders after forgot password","UI","otp-screen","visible","High"),
    ("OTP 6-digit input accepts only numbers","UI","otp-input","numeric","High"),
    ("OTP resend button visible after 60 seconds","UI","otp-resend","visible","Medium"),
    ("New password form shows after OTP verified","UI","new-pwd-form","visible","Critical"),
    ("Google Sign-In button visible on login page","UI","google-btn","visible","High"),
    ("Apple Sign-In button visible on login page","UI","apple-btn","visible","High"),
    ("Remember Me checkbox works on login","UI","remember-me","checked","Medium"),
    ("Logout button in navbar logs out user","UI","logout-btn","logout","Critical"),
    ("Logout clears local storage & session","UI","logout-clear","cleared","Critical"),
    ("Auto-logout after 30 minutes inactivity","UI","auto-logout","triggered","High"),
    ("2FA setup page renders QR code","UI","2fa-qr","visible","High"),
    ("2FA TOTP input accepts 6-digit code","UI","2fa-input","accepts","High"),
    ("Account locked message after 5 failed logins","UI","account-locked","message","Critical"),
    ("Password show/hide toggle works","UI","pwd-toggle","works","Medium"),
    ("Email field auto-fills from saved credentials","UI","autofill","works","Low"),
    ("Change password form validates current password","UI","change-pwd","validates","High"),
    ("Session expiry banner shown when token near expiry","UI","session-banner","shown","High"),
    ("Login page accessible via keyboard only","UI","login-a11y","accessible","High"),
    ("Login error message ARIA role=alert set","UI","login-aria","set","High"),
    ("Register terms checkbox required before submit","UI","terms-check","required","Medium"),
    ("Profile avatar shown in navbar after login","UI","profile-avatar","visible","Medium"),
    ("Edit profile form saves changes successfully","UI","edit-profile","saved","High"),
  ]),
  ("Offer Analyzer UI", [
    ("Offer text textarea accepts multi-line input","UI","offer-textarea","accepts","Critical"),
    ("Analyze button triggers loading state","UI","analyze-btn","loading","Critical"),
    ("Risk score gauge renders after analysis","UI","risk-gauge","visible","Critical"),
    ("Red flags list renders after analysis","UI","red-flags-list","visible","Critical"),
    ("Safe offer shows green score badge","UI","safe-badge","green","Critical"),
    ("High risk offer shows red score badge","UI","risk-badge","red","Critical"),
    ("PDF upload button accepts .pdf files","UI","pdf-upload","accepts","Critical"),
    ("PDF upload rejects non-PDF files","UI","pdf-reject","rejects","High"),
    ("PDF upload shows file name after selection","UI","pdf-filename","shown","Medium"),
    ("PDF upload progress bar renders","UI","pdf-progress","visible","Medium"),
    ("Scan result AI explanation text rendered","UI","ai-explanation","visible","High"),
    ("Share report button generates link","UI","share-btn","generates","High"),
    ("Copy link button copies to clipboard","UI","copy-link","copies","Medium"),
    ("Download PDF report button works","UI","download-pdf","works","High"),
    ("QR code displayed for report sharing","UI","qr-code","visible","Medium"),
    ("Re-scan button available after first scan","UI","rescan-btn","visible","Medium"),
    ("Compare reports button renders","UI","compare-btn","visible","Low"),
    ("Feedback rating stars submit correctly","UI","feedback-stars","submits","Low"),
    ("Batch analyze accepts multiple text entries","UI","batch-input","accepts","Medium"),
    ("Batch analyze shows all results in list","UI","batch-results","visible","Medium"),
    ("Category badge shown for detected scam type","UI","category-badge","visible","High"),
    ("Urgency level indicator rendered","UI","urgency-indicator","visible","Medium"),
    ("Salary anomaly warning highlighted","UI","salary-warning","highlighted","High"),
    ("Domain mismatch warning highlighted","UI","domain-warning","highlighted","High"),
    ("Payment demand scam flag highlighted","UI","payment-flag","highlighted","Critical"),
    ("Export JSON button downloads file","UI","export-json","downloads","Low"),
    ("Offer analyzer page renders on mobile","UI","analyzer-mobile","rendered","High"),
    ("Offer analyzer accessible via keyboard","UI","analyzer-a11y","accessible","High"),
    ("Empty textarea shows validation error on submit","UI","empty-textarea","error","High"),
    ("Analysis history stored in scan history","UI","analysis-history","stored","High"),
    ("Scan count badge updates after new scan","UI","scan-count","updated","Medium"),
    ("Language selector toggles Hindi/English UI","UI","lang-toggle","switches","Medium"),
    ("PIN protect shared report modal renders","UI","pin-modal","visible","Medium"),
    ("Report not found page shown for invalid link","UI","report-404","shown","Medium"),
    ("Offer analyzer benchmark score displayed","UI","benchmark-score","displayed","Critical"),
  ]),
  ("Company Verifier UI", [
    ("Company name search input accepts text","UI","company-input","accepts","Critical"),
    ("Verify button triggers loading state","UI","verify-btn","loading","Critical"),
    ("Verified company shows green trust badge","UI","trust-badge-green","visible","Critical"),
    ("Unverified company shows red warning badge","UI","trust-badge-red","visible","Critical"),
    ("GSTIN input field accepts 15-char GSTIN","UI","gstin-input","accepts","Critical"),
    ("GSTIN lookup renders company legal name","UI","gstin-result","rendered","Critical"),
    ("WHOIS domain input accepts domain string","UI","whois-input","accepts","Critical"),
    ("WHOIS result shows domain age in days","UI","whois-age","shown","Critical"),
    ("WHOIS result highlights domain <180 days old","UI","whois-warn","highlighted","Critical"),
    ("SSL status shown on WHOIS result","UI","ssl-status","shown","High"),
    ("DNS MX records indicator shown","UI","dns-mx","shown","High"),
    ("MCA CIN search renders director list","UI","mca-directors","rendered","High"),
    ("Scorecard radar chart renders correctly","UI","scorecard-chart","rendered","High"),
    ("Bookmark button saves company to favorites","UI","bookmark-btn","saves","Medium"),
    ("Bookmarks page lists all saved companies","UI","bookmarks-list","visible","Medium"),
    ("Remove bookmark removes from list","UI","remove-bookmark","removes","Medium"),
    ("Company reviews list renders on scorecard","UI","reviews-list","visible","Low"),
    ("Submit review form accepts rating & comment","UI","review-form","accepts","Low"),
    ("Report fraud form renders and submits","UI","report-fraud","submits","High"),
    ("Autocomplete dropdown shows top 5 suggestions","UI","autocomplete","shows","High"),
    ("Bulk verify accepts 10 comma-separated domains","UI","bulk-verify","accepts","High"),
    ("Trending companies list renders on homepage","UI","trending","visible","Low"),
    ("Email domain verify input renders result","UI","email-verify","rendered","High"),
    ("Export PDF scorecard button downloads file","UI","export-scorecard","downloads","Medium"),
    ("Empty search shows validation error","UI","empty-search","error","High"),
    ("Company verifier accessible via keyboard","UI","verifier-a11y","accessible","High"),
    ("Company verifier page renders on mobile","UI","verifier-mobile","rendered","High"),
    ("Similar companies section renders","UI","similar-companies","visible","Low"),
    ("History of company lookups shown in history","UI","company-history","shown","Medium"),
    ("Trust badge embeddable widget code copyable","UI","badge-widget","copyable","Low"),
    ("Subscribe alerts toggle button works","UI","subscribe-alerts","works","Low"),
    ("Industry average benchmark section renders","UI","industry-avg","visible","Low"),
    ("Company share link copied to clipboard","UI","company-share","copied","Low"),
    ("WHOIS result cached badge shown for cached response","UI","whois-cache","shown","Medium"),
    ("Company benchmark score displayed","UI","co-benchmark","displayed","Critical"),
  ]),
  ("Blacklist & Scammer Search UI", [
    ("Blacklist search input accepts email/phone","UI","bl-search","accepts","Critical"),
    ("Search results list renders correctly","UI","bl-results","visible","Critical"),
    ("Scammer card shows name, email, category","UI","scammer-card","visible","Critical"),
    ("Upvote button increments vote count","UI","upvote-btn","increments","High"),
    ("Downvote button decrements vote count","UI","downvote-btn","decrements","High"),
    ("Vote buttons disabled after user votes","UI","vote-disabled","disabled","High"),
    ("Category filter dropdown works","UI","category-filter","filters","High"),
    ("Date range filter renders results","UI","date-filter","filters","High"),
    ("Pagination renders next/prev buttons","UI","pagination","visible","High"),
    ("Report Scammer form renders all fields","UI","report-form","visible","Critical"),
    ("Evidence file upload accepts images","UI","evidence-upload","accepts","High"),
    ("Report form validation shows errors on empty submit","UI","report-validate","errors","High"),
    ("Report submitted success toast shown","UI","report-toast","shown","High"),
    ("Export CSV button downloads .csv file","UI","export-csv","downloads","High"),
    ("RSS feed link renders and opens","UI","rss-link","opens","Low"),
    ("Phone number search renders scammer result","UI","phone-search","renders","Critical"),
    ("Email search renders scammer result","UI","email-search","renders","Critical"),
    ("UPI ID search renders scammer result","UI","upi-search","renders","Critical"),
    ("Flag abusive button shows confirmation modal","UI","flag-abusive","modal","Medium"),
    ("Top voted tab renders most voted scammers","UI","top-voted","renders","Low"),
    ("Recent tab renders latest scammer reports","UI","recent-tab","renders","Low"),
    ("Admin verify button visible to admin users","UI","admin-verify","visible","High"),
    ("Admin reject button visible to admin users","UI","admin-reject","visible","High"),
    ("Analytics chart renders monthly trends","UI","analytics-chart","renders","Low"),
    ("Scammer profile detail page renders","UI","scammer-detail","renders","High"),
    ("Share report link copied to clipboard","UI","share-report","copied","Medium"),
    ("Subscribe alerts toggle saves preference","UI","bl-subscribe","saved","Low"),
    ("Bulk check form accepts 50 email entries","UI","bulk-check","accepts","High"),
    ("Zero results message shown for no match","UI","no-results","shown","Medium"),
    ("Blacklist search accessible via keyboard","UI","bl-a11y","accessible","High"),
    ("Blacklist page renders on mobile","UI","bl-mobile","renders","High"),
    ("Company name search renders results","UI","company-search","renders","High"),
    ("Search term highlighted in results","UI","search-highlight","highlighted","Low"),
    ("Report categories list shown in filter","UI","report-cats","shown","Medium"),
    ("Blacklist benchmark score displayed","UI","bl-benchmark","displayed","Critical"),
  ]),
  ("Resume Privacy Scanner UI", [
    ("Resume upload button accepts PDF/DOCX","UI","resume-upload","accepts","Critical"),
    ("Resume upload rejects .exe and .zip files","UI","resume-reject","rejects","High"),
    ("Upload progress bar renders during upload","UI","resume-progress","visible","Medium"),
    ("Scan result shows PII risk indicators","UI","pii-indicators","visible","Critical"),
    ("Aadhaar number detected highlighted in red","UI","aadhaar-flag","highlighted","Critical"),
    ("PAN card number detected highlighted in red","UI","pan-flag","highlighted","Critical"),
    ("Phone number exposure warning shown","UI","phone-flag","shown","High"),
    ("Email exposure warning shown","UI","email-flag","shown","High"),
    ("ATS compatibility score progress bar renders","UI","ats-score","visible","High"),
    ("Auto-redact button generates sanitized PDF","UI","auto-redact","generates","Critical"),
    ("Redacted PDF download button works","UI","redacted-download","works","Critical"),
    ("Privacy score badge shown (0-100)","UI","privacy-badge","visible","Critical"),
    ("Custom redact input accepts user text","UI","custom-redact","accepts","High"),
    ("ATS keywords suggestion list renders","UI","ats-keywords","visible","Medium"),
    ("Readability score shown after scan","UI","readability","shown","Low"),
    ("Hidden text detection result shown","UI","hidden-text","shown","High"),
    ("Compare two resumes side-by-side view","UI","resume-compare","renders","Low"),
    ("Report delete button removes report","UI","report-delete","removes","Medium"),
    ("Share link button generates password-protected link","UI","share-link","generates","Medium"),
    ("Privacy badge SVG embeddable code shown","UI","badge-code","shown","Low"),
    ("Export summary PDF button downloads file","UI","export-summary","downloads","Low"),
    ("Font safety check result renders","UI","font-check","renders","Low"),
    ("Scan history stores resume privacy audits","UI","resume-history","stored","High"),
    ("Error shown for password-protected PDF","UI","pwd-pdf-error","shown","High"),
    ("Error shown for corrupted document","UI","corrupt-error","shown","High"),
    ("Resume scanner page renders on mobile","UI","scanner-mobile","renders","High"),
    ("Resume scanner accessible via keyboard","UI","scanner-a11y","accessible","High"),
    ("Rate limit message shown after 20 scans","UI","scanner-ratelimit","shown","High"),
    ("Auto-delete notice shown (24 hours)","UI","auto-delete","shown","Medium"),
    ("Scan stats counter shown on page","UI","scan-stats","shown","Low"),
    ("Resume benchmark score displayed","UI","resume-benchmark","displayed","Critical"),
    ("Privacy score color coded (green/amber/red)","UI","score-color","colored","High"),
    ("Scan result timestamp shown","UI","scan-timestamp","shown","Low"),
    ("File name shown after upload","UI","file-name","shown","Medium"),
    ("Multiple scans listed in history tab","UI","history-tab","listed","High"),
  ]),
  ("Scan History & Dashboard UI", [
    ("Dashboard shows total scan count cards","UI","scan-cards","visible","Critical"),
    ("Dashboard shows offer scans count","UI","offer-count","visible","High"),
    ("Dashboard shows company scans count","UI","company-count","visible","High"),
    ("Dashboard shows resume scans count","UI","resume-count","visible","High"),
    ("Recent activity list renders on dashboard","UI","recent-activity","visible","Critical"),
    ("Risk trend chart renders on dashboard","UI","risk-chart","renders","High"),
    ("Scan history list renders all entries","UI","history-list","visible","Critical"),
    ("Filter by scan type (offer/company/resume)","UI","type-filter","filters","High"),
    ("Search history by keyword works","UI","history-search","works","High"),
    ("Date range filter filters correctly","UI","date-range","filters","Medium"),
    ("Delete single history item works","UI","delete-item","works","High"),
    ("Batch delete multiple items works","UI","batch-delete","works","High"),
    ("Clear all history confirmation modal shown","UI","clear-confirm","shown","High"),
    ("Favorite star toggle works","UI","fav-toggle","works","Medium"),
    ("Favorites list shows starred items","UI","fav-list","visible","Medium"),
    ("Export Excel button downloads file","UI","export-excel","downloads","High"),
    ("Export PDF summary button downloads file","UI","export-pdf","downloads","Medium"),
    ("Restore deleted item within 30 days works","UI","restore-item","works","Low"),
    ("Tag input accepts custom label","UI","tag-input","accepts","Low"),
    ("Tags list shown in history filter","UI","tags-filter","shown","Low"),
    ("Notes textarea saves correctly","UI","notes-save","saves","Low"),
    ("Storage usage indicator shown","UI","storage-usage","shown","Low"),
    ("Auto-delete settings dropdown works","UI","auto-delete","works","Low"),
    ("Share batch link generates for selection","UI","share-batch","generates","Low"),
    ("Summary card widget renders","UI","summary-card","renders","Low"),
    ("Re-verify button triggers background scan","UI","re-verify","triggers","Medium"),
    ("History page accessible via keyboard","UI","history-a11y","accessible","High"),
    ("History page renders on mobile","UI","history-mobile","renders","High"),
    ("Empty history shows placeholder illustration","UI","empty-history","shown","Medium"),
    ("History item click opens detail view","UI","history-click","opens","High"),
    ("Category badge shown on each history card","UI","category-badge","shown","Medium"),
    ("Risk score shown on each history card","UI","risk-score","shown","High"),
    ("Timestamp shown on each history card","UI","timestamp","shown","Medium"),
    ("Search no results message shown","UI","no-history","shown","Medium"),
    ("History benchmark score displayed","UI","history-benchmark","displayed","Critical"),
  ]),
  ("UI Components, Accessibility & Responsiveness", [
    ("Primary button hover state renders","UI","btn-hover","renders","Low"),
    ("Primary button focus outline visible (a11y)","UI","btn-focus","visible","High"),
    ("Form input focus border highlight visible","UI","input-focus","visible","High"),
    ("Dropdown menu opens and closes on click","UI","dropdown","opens","Medium"),
    ("Modal dialog traps keyboard focus (a11y)","UI","modal-focus","trapped","Critical"),
    ("Modal closes on ESC key press","UI","modal-esc","closes","High"),
    ("Modal closes on backdrop click","UI","modal-backdrop","closes","Medium"),
    ("Toast notifications render and auto-dismiss","UI","toast","renders","High"),
    ("Success toast shows green color","UI","toast-success","green","Medium"),
    ("Error toast shows red color","UI","toast-error","red","High"),
    ("Warning toast shows amber color","UI","toast-warning","amber","Medium"),
    ("Skeleton loading placeholders shown while fetching","UI","skeleton","shown","Medium"),
    ("Infinite scroll loads more items","UI","infinite-scroll","loads","Medium"),
    ("Search input debounce prevents excessive API calls","UI","search-debounce","works","High"),
    ("Dark mode toggle switches theme","UI","dark-mode","switches","Medium"),
    ("Light mode toggle switches theme","UI","light-mode","switches","Medium"),
    ("System theme preference respected on load","UI","system-theme","respected","Low"),
    ("Font size increases with browser zoom 150%","UI","font-zoom","scales","Low"),
    ("Images have alt text for screen readers","UI","img-alt","set","High"),
    ("All buttons have aria-label attributes","UI","btn-aria","set","High"),
    ("Color contrast ratio meets WCAG AA standard","UI","color-contrast","passes","Critical"),
    ("Skip to main content link present","UI","skip-link","present","High"),
    ("ARIA live regions announce dynamic updates","UI","aria-live","announces","High"),
    ("Tab order is logical on all pages","UI","tab-order","logical","Critical"),
    ("Focus returns to trigger after modal close","UI","focus-return","returns","High"),
    ("Touch targets minimum 44x44px on mobile","UI","touch-target","sized","Critical"),
    ("Pinch-to-zoom not blocked on mobile","UI","pinch-zoom","works","Medium"),
    ("Horizontal scroll absent on all pages","UI","no-h-scroll","absent","High"),
    ("RTL layout toggle works for Arabic locale","UI","rtl-layout","works","Medium"),
    ("Print stylesheet renders clean layout","UI","print-css","renders","Low"),
    ("Favicon displayed in browser tab","UI","favicon","shown","Low"),
    ("Progress bar renders for long operations","UI","progress-bar","renders","Medium"),
    ("Empty state illustrations render correctly","UI","empty-state","renders","Medium"),
    ("Tooltip renders on icon hover","UI","tooltip","renders","Low"),
    ("UI component benchmark score passed","UI","ui-benchmark","passed","Critical"),
  ]),
  ("Performance, SEO & PWA Checks", [
    ("First Contentful Paint (FCP) under 0.8s","PERF","FCP","<0.8s","Critical"),
    ("Largest Contentful Paint (LCP) under 1.2s","PERF","LCP","<1.2s","Critical"),
    ("Total Blocking Time (TBT) under 50ms","PERF","TBT","<50ms","Critical"),
    ("Cumulative Layout Shift (CLS) score 0.00","PERF","CLS","0.00","Critical"),
    ("Time to Interactive (TTI) under 2s","PERF","TTI","<2s","High"),
    ("JavaScript bundle size under 300KB gzipped","PERF","JS-size","<300KB","High"),
    ("CSS bundle size under 50KB gzipped","PERF","CSS-size","<50KB","High"),
    ("Total page weight under 500KB on first load","PERF","page-weight","<500KB","High"),
    ("Images served in WebP/AVIF format","PERF","img-format","webp","Medium"),
    ("Images have explicit width & height attributes","PERF","img-dims","set","Medium"),
    ("Lazy loading applied to offscreen images","PERF","lazy-load","applied","Medium"),
    ("Critical CSS inlined in <head>","PERF","critical-css","inlined","Medium"),
    ("Unused CSS removed by purge step","PERF","purge-css","done","Low"),
    ("HTTP/2 protocol used for all requests","PERF","http2","used","High"),
    ("Cache-Control headers set on all static assets","PERF","cache-ctrl","set","High"),
    ("Service Worker registered successfully","PWA","sw-register","registered","High"),
    ("App installable via browser install prompt","PWA","install-prompt","shown","High"),
    ("Offline page shown when network unavailable","PWA","offline-page","shown","Critical"),
    ("Web App Manifest JSON valid","PWA","manifest","valid","High"),
    ("App icons defined for all sizes (192/512px)","PWA","app-icons","defined","Medium"),
    ("Meta viewport tag present","SEO","meta-viewport","present","Critical"),
    ("Canonical URL meta tag present","SEO","canonical","present","High"),
    ("Open Graph og:title tag present","SEO","og-title","present","High"),
    ("Open Graph og:description tag present","SEO","og-desc","present","High"),
    ("Open Graph og:image tag present","SEO","og-image","present","Medium"),
    ("Twitter card meta tags present","SEO","twitter-card","present","Medium"),
    ("Structured data JSON-LD schema present","SEO","schema-ld","present","Medium"),
    ("Sitemap.xml available at /sitemap.xml","SEO","sitemap","available","Medium"),
    ("Robots.txt available at /robots.txt","SEO","robots","available","Medium"),
    ("Lighthouse performance score >= 90","PERF","lighthouse",">=90","Critical"),
    ("Lighthouse accessibility score >= 90","PERF","lh-a11y",">=90","Critical"),
    ("Lighthouse SEO score >= 90","PERF","lh-seo",">=90","High"),
    ("Lighthouse PWA score 100","PERF","lh-pwa","100","High"),
    ("No console errors on page load","PERF","console-errors","0","Critical"),
    ("Frontend performance benchmark score passed","PERF","fe-benchmark","passed","Critical"),
  ]),
]

tcs = []
ctr = 1
for cat, tests in cats:
    for title, method, endpoint, expected, severity in tests:
        tcs.append({
            "id": f"FTC-{ctr:03d}",
            "category": cat,
            "title": title,
            "method": method,
            "endpoint": endpoint,
            "expected": expected,
            "severity": severity,
            "description": f"Frontend E2E test: {title}",
            "assertion": f"Expected result '{expected}' verified for {endpoint}",
        })
        ctr += 1

out = {"suite_name": "InternSafe Frontend UI Test Suite", "total_cases": len(tcs), "test_cases": tcs}
os.makedirs("frontend test", exist_ok=True)
with open("frontend test/input.json", "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2)
print(f"Generated frontend test/input.json with {len(tcs)} test cases!")
